name: 'Reviewers Chooser'
description: 'Chooser reviewers automatically to PR'
inputs:
  amount-of-reviewers:
    description: 'Amount of reviewers'
    required: false
    default: '2'
  review-complexity:
    description: 'The complexity of the PR to review'
    required: true
    default: 'medium'
  token:
    description: 'GitHub token'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
